      var param = {
        initZoom: 11,
        minZoom: 5,
        maxZoom: 11,
        wrap: false,
        attribution: '&copy;sixdozen',
        tileString: 'ahh.nuts',
        doCustomTileUrl: true,
        tileLookup: {
          '5,6': 'http://assets.sixdozen.com/escape/waters-edge-top-left-corner',
          '6,6': 'http://assets.sixdozen.com/escape/california-coast-top-edge',
          '7,6': 'http://assets.sixdozen.com/escape/california-choice-top-edge',
          '8,6': 'http://assets.sixdozen.com/escape/lands-edge-top',
          '9,6': 'http://assets.sixdozen.com/escape/lands-edge-top-right-corner',
          '5,7': 'http://assets.sixdozen.com/escape/waters-edge-left',
          '6,7': 'http://assets.sixdozen.com/escape/california-coast',
          '7,7': 'http://assets.sixdozen.com/escape/california-choice',
          '8,7': 'http://assets.sixdozen.com/escape/california-inland',
          '9,7': 'http://assets.sixdozen.com/escape/lands-edge-right',
          '5,8': 'http://assets.sixdozen.com/escape/waters-edge-left',
          '6,8': 'http://assets.sixdozen.com/escape/mexico-coast',
          '7,8': 'http://assets.sixdozen.com/escape/mexico-choice',
          '8,8': 'http://assets.sixdozen.com/escape/mexico-inland',
          '9,8': 'http://assets.sixdozen.com/escape/lands-edge-right',
          '5,9': 'http://assets.sixdozen.com/escape/waters-edge-bottom-left-corner',
          '6,9': 'http://assets.sixdozen.com/escape/waters-edge-bottom',
          '7,9': 'http://assets.sixdozen.com/escape/mexico-choice-bottom-edge',
          '8,9': 'http://assets.sixdozen.com/escape/lands-edge-bottom',
          '9,9': 'http://assets.sixdozen.com/escape/lands-edge-bottom-right-corner',
        },
//        initialBounds: [[9.1/16.0, 5.9/16.0], [6.9/16.0, 9.1/16.0]],
//        initialBounds: [[9.1/16.0, 5.9/16.0], [6.9/16.0, 9.1/16.0]],
        bounds : {
          'xmin': 5.75,
          'ymin': 6.75,
          'xmax': 9.25,
          'ymax': 9.25,
        }
      }    

