      var param = {
        initZoom: 11,
        minZoom: 5,
        maxZoom: 11,
        wrap: false,
        attribution: '&copy;sixdozen',
        tileString: 'ahh.nuts',
        doCustomTileUrl: true,
        tileLookup: {
          '5,6': '/escape-final/waters-edge-top-left-corner',
          '6,6': '/escape-final/california-coast-top-edge',
          '7,6': '/escape-final/california-choice-top-edge',
          '8,6': '/escape-final/lands-edge-top',
          '9,6': '/escape-final/lands-edge-top-right-corner',
          '5,7': '/escape-final/waters-edge-left',
          '6,7': '/escape-final/california-coast',
          '7,7': '/escape-final/california-choice',
          '8,7': '/escape-final/california-inland',
          '9,7': '/escape-final/lands-edge-right',
          '5,8': '/escape-final/waters-edge-left',
          '6,8': '/escape-final/mexico-coast',
          '7,8': '/escape-final/mexico-choice',
          '8,8': '/escape-final/mexico-inland',
          '9,8': '/escape-final/lands-edge-right',
          '5,9': '/escape-final/waters-edge-bottom-left-corner',
          '6,9': '/escape-final/waters-edge-bottom',
          '7,9': '/escape-final/mexico-choice-bottom-edge',
          '8,9': '/escape-final/lands-edge-bottom',
          '9,9': '/escape-final/lands-edge-bottom-right-corner',
        },
//        initialBounds: [[9.1/16.0, 5.9/16.0], [6.9/16.0, 9.1/16.0]],
//        initialBounds: [[9.1/16.0, 5.9/16.0], [6.9/16.0, 9.1/16.0]],
        bounds : {
          'xmin': 5.75,
          'ymin': 6.75,
          'xmax': 9.25,
          'ymax': 9.25,
        }
      }    

